#!/usr/bin/env bash

curl --verbose --data-ascii '
  <html>
    <head>
      Stuff in head
    </head>
    <body>
      <script>alert(123);</script>
      <h1>h1</h1>
      <p style = "color:red;background-color:eval('white');">
        paragraph style="test fail" <  >
      </p>
      <script>alert('FAIL!!!')</script>
      <button onclick="alert(1)">test</button>
    </body>
  </html>
  ' \
  -H 'Content-Type: text/html; charset=utf-8' \
  -H 'Accept: application/json' \
  -X POST http://localhost:5000/
